services:
  - type: web
    name: nasa-space-apps-backend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    region: oregon
    branch: main
    envVars:
      - key: PYTHONPATH
        value: /app
      - key: PYTHONUNBUFFERED
        value: 1
    healthCheckPath: /docs
    autoDeploy: true
